import type { LanguageCode } from "@/types/jcb";
const en = {
  home:"Home", one:"JCB ONE", app:"App", legal:"Legal", language:"Language",
  welcome:"Welcome to JCB ONE", intro:"Access your JCB machine information quickly and easily.",
  detected:"Machine information detected", missing:"Scan a JCB ONE QR code to access machine-specific information.",
  invalid:"Unable to identify the machine.", scanEnter:"Scan / Enter VIN", tryAgain:"Try again",
  machine:"Machine", vin:"VIN", serial:"Serial Number", status:"Status", identified:"Machine Identified",
  viewMachine:"View Machine", continue:"Continue to JCB ONE", machineInfo:"Machine Information", documents:"Documents",
  how:"How JCB ONE works", scan:"Scan", scanText:"Scan the JCB ONE QR code.", identify:"Identify", identifyText:"Your machine information is identified.", access:"Access", accessText:"Access the information you need.",
  downloadJcb:"Download JCB ONE", appStore:"App Store", googlePlay:"Google Play", download:"Download",
  privacy:"Privacy Policy", terms:"Terms & Conditions", qrTest:"QR Code Test", testQR:"Test QR", copyURL:"Copy URL", copied:"Copied",
  chooseLanguage:"Choose your preferred language", storeContent:"Store content", screenshots:"Store screenshots",
};
export type TranslationKey = keyof typeof en;
const variants: Record<LanguageCode, Partial<Record<TranslationKey,string>>> = {
  en_US: {}, en_GB: {},
  es_ES: {home:"Inicio",app:"Aplicación",legal:"Legal",language:"Idioma",welcome:"Bienvenido a JCB ONE",intro:"Acceda a la información de su máquina JCB de forma rápida y sencilla.",detected:"Información de la máquina detectada",missing:"Escanee un código QR de JCB ONE para acceder a información específica de la máquina.",invalid:"No se puede identificar la máquina.",scanEnter:"Escanear / Introducir VIN",tryAgain:"Intentar de nuevo",machine:"Máquina",serial:"Número de serie",status:"Estado",identified:"Máquina identificada",viewMachine:"Ver máquina",continue:"Continuar a JCB ONE",machineInfo:"Información de la máquina",documents:"Documentos",how:"Cómo funciona JCB ONE",scan:"Escanear",scanText:"Escanee el código QR de JCB ONE.",identify:"Identificar",identifyText:"Se identifica la información de su máquina.",access:"Acceder",accessText:"Acceda a la información que necesita.",downloadJcb:"Descargar JCB ONE",download:"Descargar",privacy:"Política de privacidad",terms:"Términos y condiciones",qrTest:"Prueba de código QR",testQR:"Probar QR",copyURL:"Copiar URL",copied:"Copiado",chooseLanguage:"Elija su idioma preferido"},
  pt_PT: {home:"Início",app:"Aplicação",legal:"Legal",language:"Idioma",welcome:"Bem-vindo ao JCB ONE",intro:"Aceda às informações da sua máquina JCB de forma rápida e fácil.",detected:"Informações da máquina detetadas",missing:"Digitalize um código QR JCB ONE para aceder a informações específicas da máquina.",invalid:"Não foi possível identificar a máquina.",scanEnter:"Digitalizar / Introduzir VIN",tryAgain:"Tentar novamente",machine:"Máquina",serial:"Número de série",status:"Estado",identified:"Máquina identificada",viewMachine:"Ver máquina",continue:"Continuar para JCB ONE",machineInfo:"Informações da máquina",documents:"Documentos",how:"Como funciona o JCB ONE",scan:"Digitalizar",scanText:"Digitalize o código QR JCB ONE.",identify:"Identificar",identifyText:"As informações da sua máquina são identificadas.",access:"Aceder",accessText:"Aceda às informações de que necessita.",downloadJcb:"Descarregar JCB ONE",download:"Descarregar",privacy:"Política de Privacidade",terms:"Termos e Condições",qrTest:"Teste de código QR",testQR:"Testar QR",copyURL:"Copiar URL",copied:"Copiado",chooseLanguage:"Escolha o seu idioma preferido"},
  de_DE: {home:"Startseite",app:"App",legal:"Rechtliches",language:"Sprache",welcome:"Willkommen bei JCB ONE",intro:"Greifen Sie schnell und einfach auf die Informationen Ihrer JCB-Maschine zu.",detected:"Maschineninformationen erkannt",missing:"Scannen Sie einen JCB ONE QR-Code, um maschinenspezifische Informationen aufzurufen.",invalid:"Die Maschine konnte nicht identifiziert werden.",scanEnter:"Scannen / VIN eingeben",tryAgain:"Erneut versuchen",machine:"Maschine",serial:"Seriennummer",status:"Status",identified:"Maschine identifiziert",viewMachine:"Maschine ansehen",continue:"Weiter zu JCB ONE",machineInfo:"Maschineninformationen",documents:"Dokumente",how:"So funktioniert JCB ONE",scan:"Scannen",scanText:"Scannen Sie den JCB ONE QR-Code.",identify:"Identifizieren",identifyText:"Ihre Maschineninformationen werden identifiziert.",access:"Zugreifen",accessText:"Greifen Sie auf die benötigten Informationen zu.",downloadJcb:"JCB ONE herunterladen",download:"Herunterladen",privacy:"Datenschutzrichtlinie",terms:"Allgemeine Geschäftsbedingungen",qrTest:"QR-Code-Test",testQR:"QR testen",copyURL:"URL kopieren",copied:"Kopiert",chooseLanguage:"Wählen Sie Ihre bevorzugte Sprache"},
};
export const translations = Object.fromEntries(Object.entries(variants).map(([key,value]) => [key,{...en,...value}])) as Record<LanguageCode, typeof en>;
export const languageNames: Record<LanguageCode,string> = {en_US:"English (US)",en_GB:"English (UK)",es_ES:"Español",pt_PT:"Português",de_DE:"Deutsch"};
