import { useEffect, useMemo, useState, type ReactNode } from "react";
import { QRCodeSVG } from "qrcode.react";
import { ArrowRight, Check, ChevronDown, Clipboard, FileText, Globe2, Menu, QrCode, ScanLine, ShieldCheck, Smartphone, X } from "lucide-react";
import heroImage from "@/assets/jcb-hero.jpg";
import excavatorImage from "@/assets/jcb-excavator.jpg";
import logo from "@/assets/jcb-logo.png.asset.json";
import { translations, languageNames, type TranslationKey } from "@/i18n/translations";
import { getMachineByQR } from "@/services/api/machines";
import { buildQRUrl, isValidQR, readQRParameters } from "@/services/qr";
import type { LanguageCode, Machine, QRInput } from "@/types/jcb";

type T = (key: TranslationKey) => string;
type LegalKind = "terms" | "privacy" | null;

function Button({ children, variant="primary", onClick, href, type="button", className="" }: { children:ReactNode; variant?:"primary"|"secondary"|"ghost"; onClick?:()=>void; href?:string; type?:"button"|"submit"; className?:string }) {
  const classes = `btn btn-${variant} ${className}`;
  return href ? <a className={classes} href={href} onClick={onClick}>{children}</a> : <button className={classes} type={type} onClick={onClick}>{children}</button>;
}

function Header({ language, setLanguage, t }: { language:LanguageCode; setLanguage:(v:LanguageCode)=>void; t:T }) {
  const [open,setOpen]=useState(false);
  const links=[["#home",t("home")],["#how",t("one")],["#download",t("app")],["#legal",t("legal")]];
  return <header className="site-header"><div className="nav-wrap">
    <a href="#home" className="brand" aria-label="JCB ONE home"><img src={logo.url} alt="JCB"/><span>ONE</span></a>
    <nav className="desktop-nav" aria-label="Main navigation">{links.map(([href,label])=><a key={href} href={href}>{label}</a>)}</nav>
    <div className="nav-tools"><label className="language-select"><Globe2 size={17}/><span className="sr-only">{t("language")}</span><select value={language} onChange={e=>setLanguage(e.target.value as LanguageCode)}>{Object.entries(languageNames).map(([code,name])=><option key={code} value={code}>{name}</option>)}</select><ChevronDown size={14}/></label>
    <button className="menu-btn" aria-label="Open menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>
  </div>{open&&<nav className="mobile-nav">{links.map(([href,label])=><a key={href} href={href} onClick={()=>setOpen(false)}>{label}<ArrowRight size={16}/></a>)}</nav>}</header>
}

function Hero({ t, onEnter }: { t:T; onEnter:(value:string)=>void }) {
  const [input,setInput]=useState("");
  return <section id="home" className="hero"><img src={heroImage} alt="Yellow backhoe loader on a construction site" width={1920} height={1080}/><div className="hero-shade"/><div className="hero-content"><p className="eyebrow">JCB ONE</p><h1>{t("welcome")}</h1><p>{t("intro")}</p><form onSubmit={e=>{e.preventDefault();onEnter(input)}}><label htmlFor="vin-entry">VIN / MACHINE ID / SERIAL NUMBER</label><div className="hero-form"><input id="vin-entry" value={input} onChange={e=>setInput(e.target.value)} placeholder="HXNEDJ3N123456789"/><Button type="submit">{t("scanEnter")} <ArrowRight size={18}/></Button></div></form></div></section>
}

function MachineIdentification({ t, manualInput }: { t:T; manualInput:string }) {
  const [machine,setMachine]=useState<Machine|null>(null); const [state,setState]=useState<"missing"|"loading"|"success"|"invalid">("loading");
  const qrInput=useMemo<QRInput|null>(()=>{
    if(manualInput) { const clean=manualInput.trim(); const type=clean.length===17?"vin":/^\d+$/.test(clean)?"serialNumber":"machineId"; return {type,value:clean}; }
    return typeof window!=="undefined"?readQRParameters(window.location.search):null;
  },[manualInput]);
  useEffect(()=>{ let active=true; if(!qrInput){setState("missing");return;} if(!isValidQR(qrInput)){setState("invalid");return;} setState("loading"); getMachineByQR(qrInput).then(data=>{if(active){setMachine(data);setState("success");}}); return()=>{active=false};},[qrInput]);
  return <section className="machine-section" aria-live="polite"><div className="content-shell">
    {state==="loading"&&<div className="machine-panel loading-panel"><div className="spinner"/><div><div className="skeleton wide"/><div className="skeleton"/></div></div>}
    {state==="missing"&&<div className="machine-panel empty-panel"><QrCode size={44}/><div><p className="eyebrow dark">QR READY</p><h2>{t("welcome")}</h2><p>{t("missing")}</p></div><Button href="#home">{t("scanEnter")}</Button></div>}
    {state==="invalid"&&<div className="machine-panel empty-panel"><X size={44}/><div><p className="eyebrow dark">QR ERROR</p><h2>{t("invalid")}</h2><p>Check the code and scan again.</p></div><Button onClick={()=>window.location.assign(window.location.pathname)}>{t("tryAgain")}</Button></div>}
    {state==="success"&&machine&&<div className="machine-panel success-panel"><div className="success-heading"><span><Check size={22}/></span><div><p className="eyebrow dark">QR CONFIRMED</p><h2>{t("detected")}</h2></div></div><div className="machine-grid"><Data label={t("machine")} value={machine.name}/><Data label={t("vin")} value={machine.vin}/><Data label={t("serial")} value={machine.serialNumber}/><Data label={t("status")} value={t("identified")} accent/></div><div className="button-row"><Button onClick={()=>document.querySelector("#machine-detail")?.scrollIntoView({behavior:"smooth"})}>{t("viewMachine")} <ArrowRight size={18}/></Button><Button variant="secondary" href="#how">{t("continue")}</Button></div></div>}
  </div></section>
}
function Data({label,value,accent=false}:{label:string;value:string;accent?:boolean}){return <div className="data-item"><span>{label}</span><strong className={accent?"status-text":""}>{value}</strong></div>}

function HowItWorks({t}:{t:T}) { const steps=[{n:"01",icon:<ScanLine/>,title:t("scan"),text:t("scanText")},{n:"02",icon:<QrCode/>,title:t("identify"),text:t("identifyText")},{n:"03",icon:<Smartphone/>,title:t("access"),text:t("accessText")}]; return <section id="how" className="how section-pad"><div className="content-shell"><p className="eyebrow dark">SIMPLE. CONNECTED.</p><h2>{t("how")}</h2><div className="steps">{steps.map((s,i)=><article key={s.n} className="step"><div className="step-top"><span>{s.n}</span>{s.icon}</div><h3>{s.title}</h3><p>{s.text}</p>{i<2&&<ArrowRight className="step-arrow"/>}</article>)}</div></div></section>}

function QRCard({ label, url, t }: {label:string;url:string;t:T}) { const [copied,setCopied]=useState(false); return <article className="qr-card"><div className="qr-box"><QRCodeSVG value={url} size={148} level="M"/></div><h3>{label}</h3><p className="code-line">{url}</p><div className="compact-actions"><Button href={url}>{t("testQR")}</Button><Button variant="ghost" onClick={()=>{navigator.clipboard.writeText(url);setCopied(true);setTimeout(()=>setCopied(false),1500)}}><Clipboard size={16}/>{copied?t("copied"):t("copyURL")}</Button></div></article> }
function QRTest({t}:{t:T}) { const samples=[{label:"Sample VIN QR Code",url:buildQRUrl("vin","HXNEDJ3N123456789")},{label:"Sample Machine QR Code",url:buildQRUrl("machineId","JCB-G125RS-001")},{label:"Sample Serial Number QR Code",url:buildQRUrl("serialNumber","1234567")}]; return <section className="qr-test section-pad"><div className="content-shell"><div className="section-heading"><div><p className="eyebrow dark">PROTOTYPE TOOLS</p><h2>{t("qrTest")}</h2></div><p>Scan with a phone camera or test directly in this prototype.</p></div><div className="qr-grid">{samples.map(s=><QRCard key={s.label} {...s} t={t}/>)}</div></div></section>}

function Download({t}:{t:T}) { const stores=[{name:t("appStore"),heading:"Download on the App Store",caption:"Scan to download JCB ONE from the Apple App Store.",url:"https://example.com/jcb-one/app-store"},{name:t("googlePlay"),heading:"Get it on Google Play",caption:"Scan to download JCB ONE from Google Play.",url:"https://example.com/jcb-one/google-play"}]; return <section id="download" className="download section-pad"><div className="content-shell"><div className="section-heading light"><div><p className="eyebrow">JCB ONE APP</p><h2>{t("downloadJcb")}</h2></div><p>Everything you need from JCB, wherever you work.</p></div><div className="store-grid">{stores.map(s=><article className="store-card" key={s.name}><div><span className="draft-tag">SAMPLE QR</span><h3>{s.heading}</h3><p>{s.caption}</p><Button href={s.url}>{s.name}<ArrowRight size={18}/></Button><small>Replace with final {s.name} URL</small></div><div className="store-qr"><QRCodeSVG value={s.url} size={154}/></div></article>)}</div></div></section>}

const screens=[{title:"Welcome",icon:<QrCode/>,copy:"Quick access to your JCB machine"},{title:"Identify",icon:<ScanLine/>,copy:"Scan and identify in seconds"},{title:"Machine",icon:<Check/>,copy:"Your JCB information in one place"},{title:"Documents",icon:<FileText/>,copy:"Access important documents"},{title:"Language",icon:<Globe2/>,copy:"Choose your preferred language"}];
function StoreReview({t}:{t:T}) { return <section id="machine-detail" className="review section-pad"><div className="content-shell"><div className="review-intro"><div><span className="draft-tag yellow">DRAFT — FOR JCB REVIEW</span><p className="eyebrow dark">{t("storeContent")}</p><h2>JCB ONE APP</h2></div><p>Your connected gateway to JCB machine information, documents and services.</p></div><div className="editorial-split"><img src={excavatorImage} alt="Yellow excavator working in a quarry" loading="lazy" width={1600} height={1000}/><div className="app-copy"><h3>Everything in one convenient experience.</h3><p>JCB ONE brings essential JCB information and services together. Access machine information, documentation and other JCB resources quickly and easily from your mobile device.</p><ul>{["Quick access to JCB machine information","Access machine documents and manuals","Simple QR-code based experience","Multi-language support","Mobile-friendly experience"].map(x=><li key={x}><Check size={17}/>{x}</li>)}</ul></div></div><div className="screens-heading"><p className="eyebrow dark">{t("screenshots")}</p><h2>Mobile app preview</h2><span>Sample screenshots for JCB review</span></div><div className="phone-strip">{screens.map((s,i)=><article className="phone" key={s.title}><div className="phone-top"><img src={logo.url} alt=""/><span>{String(i+1).padStart(2,"0")}</span></div><div className="phone-stage">{s.icon}<strong>{s.title}</strong></div><p>{s.copy}</p></article>)}</div><Metadata/></div></section> }
function Metadata(){const rows=[["App Name","JCB ONE"],["Subtitle / Short Description","Your connected gateway to JCB machine information, documents and services."],["Keywords","JCB, machines, documents, QR, equipment"],["Category","Business / Productivity — to be confirmed"],["Age Rating","To be confirmed by JCB"],["Privacy Policy URL","To be provided by JCB"],["Terms & Conditions URL","To be provided by JCB"],["Support URL","To be provided by JCB"],["Developer / Publisher","JCB — to be confirmed"],["Copyright","To be provided by JCB"],["Feature graphic","1024 × 500 px required for Google Play"]];return <div className="metadata"><div className="metadata-head"><div><p className="eyebrow dark">STORE METADATA</p><h2>Submission checklist</h2></div><span className="draft-tag yellow">JCB TEAM REVIEW REQUIRED</span></div><div className="metadata-table">{rows.map(([k,v])=><div key={k}><strong>{k}</strong><span>{v}</span></div>)}</div></div>}

const legalData={terms:["Introduction","Use of JCB ONE","User Responsibilities","Account and Access","Intellectual Property","Third-Party Services","Availability of Services","Limitation of Liability","Changes to Terms","Contact Information"],privacy:["Introduction","Information We Collect","How We Use Information","Information Sharing","Data Retention","Data Security","User Rights","Cookies and Similar Technologies","Children's Privacy","International Data Transfers","Changes to this Privacy Policy","Contact Us"]};
function LegalModal({kind,onClose,t}:{kind:Exclude<LegalKind,null>;onClose:()=>void;t:T}){const title=kind==="terms"?t("terms"):t("privacy");return <div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="legal-modal" role="dialog" aria-modal="true" aria-labelledby="legal-title"><header><div><p className="eyebrow dark">JCB ONE LEGAL</p><h2 id="legal-title">{title}</h2></div><button aria-label="Close" onClick={onClose}><X/></button></header><div className="legal-notice"><ShieldCheck/><p>Draft placeholder content. Final {title} will be provided and approved by JCB.</p></div><div className="legal-meta"><span>Effective Date: <strong>To be provided by JCB</strong></span><span>Version: <strong>Draft</strong></span></div><ol>{legalData[kind].map(item=><li key={item}><h3>{item}</h3><p>Placeholder section reserved for content to be reviewed and approved by the JCB legal team.</p></li>)}</ol></div></div>}
function LanguageBand({t,language,setLanguage}:{t:T;language:LanguageCode;setLanguage:(v:LanguageCode)=>void}){return <section className="language-band section-pad"><div className="content-shell"><Globe2/><div><p className="eyebrow dark">{t("language")}</p><h2>{t("chooseLanguage")}</h2></div><div className="language-buttons">{Object.entries(languageNames).map(([code,name])=><Button key={code} variant={language===code?"primary":"secondary"} onClick={()=>setLanguage(code as LanguageCode)}>{name}</Button>)}</div></div></section>}
function Footer({t,onLegal}:{t:T;onLegal:(kind:Exclude<LegalKind,null>)=>void}){return <footer id="legal"><div className="content-shell footer-main"><div className="brand footer-brand"><img src={logo.url} alt="JCB"/><span>ONE</span></div><p>One connected experience for JCB machine information.</p><div><button onClick={()=>onLegal("terms")}>{t("terms")}</button><button onClick={()=>onLegal("privacy")}>{t("privacy")}</button></div></div><div className="content-shell copyright">© 2026 JCB. Prototype content for review.</div></footer>}

export default function JcbOneApp(){const [language,setLanguageState]=useState<LanguageCode>("en_US");const [manualInput,setManualInput]=useState("");const [legal,setLegal]=useState<LegalKind>(null);useEffect(()=>{const stored=localStorage.getItem("jcb-one-language") as LanguageCode|null;if(stored&&languageNames[stored])setLanguageState(stored)},[]);const setLanguage=(v:LanguageCode)=>{setLanguageState(v);localStorage.setItem("jcb-one-language",v)};const t:T=(key)=>translations[language][key];return <><Header language={language} setLanguage={setLanguage} t={t}/><main><Hero t={t} onEnter={value=>{setManualInput(value);setTimeout(()=>document.querySelector(".machine-section")?.scrollIntoView({behavior:"smooth"}),0)}}/><MachineIdentification t={t} manualInput={manualInput}/><HowItWorks t={t}/><QRTest t={t}/><Download t={t}/><StoreReview t={t}/><LanguageBand t={t} language={language} setLanguage={setLanguage}/></main><Footer t={t} onLegal={setLegal}/>{legal&&<LegalModal kind={legal} onClose={()=>setLegal(null)} t={t}/>}</>}
